# GoReleaser 配置文件
# 用于自动构建多平台二进制并发布到 GitHub Release

version: 2

project_name: jvp

# 构建前钩子：构建前端并复制到 static 目录
before:
  hooks:
    - sh -c "cd web-vite && bun install && bun run build"
    - sh -c "rm -rf ./internal/jvp/api/static && mkdir -p ./internal/jvp/api/static"
    - sh -c "cp -r ./web-vite/dist/* ./internal/jvp/api/static/"
    # 生成 changelog（从上一个正式版本开始计算）
    - sh -c "./scripts/changelog.sh"

# 构建配置
builds:
  - id: jvp
    main: ./cmd/jvp/main.go
    binary: jvp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/jimmicro/version.GitTag={{.Tag}}'
      - -X 'github.com/jimmicro/version.BuildTime={{.Date}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# 归档配置
archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    # 使用 none* 来避免匹配任何文件，从而只包含二进制文件
    # 如果不设置 files，goreleaser 默认会包含 LICENSE*、README*、CHANGELOG 等文件
    files:
      - none*

# GitHub Release 配置
release:
  github:
    owner: jimyag
    name: jvp
  mode: replace
  # 自定义 release notes 通过 CI 命令行参数传入：
  # goreleaser release --release-notes=CHANGELOG.tmp.md

# Docker 镜像配置（使用 dockers_v2）
# 简化配置：GoReleaser 会自动构建多架构镜像并创建 manifest
dockers_v2:
  - platforms:
      - linux/amd64
      - linux/arm64
    images:
      - "ghcr.io/jimyag/jvp"
    tags:
      - "{{ .Tag }}"
      - "latest"
    dockerfile: Dockerfile
    sbom: none # 禁用 SBOM，避免 docker driver 不支持 attestation 的问题
    # 额外需要复制到构建上下文的文件
    extra_files:
      - docker/entrypoint.sh
      - docker/supervisord.conf
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.title: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Tag}}"
